---
name: IO-EventMux
version: 1.00
author:
  - 'Jonas Jensen <jonas@infopro.dk>,Troels Liebe Bentsen <troels@infopro.dk>'
abstract: "Multiplexer for sockets, pipes and any other types of\nfilehandles that you can set O_NONBLOCK on and does buffering for the user."
license: perl
build_requires:
  Test::More: 0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  IO::EventMux:
    file: lib/IO/EventMux.pm
    version: 1.00
resources:
  license: http://dev.perl.org/licenses/
